server:
  port: 8080

spring:
  data:
    jpa:
      repositories:
        enabled: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/main-service
    driver: com.mysql.jdbc.Driver
    username: root
    password: secretpass


