spring:
  application:
    name: main-service
  mvc:
    log-request-details: true
  data:
    jpa:
      repositories:
        enabled: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/main-service
    driver: com.mysql.jdbc.Driver
    username: root
    password: secretpass
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    root: INFO


